version: "2.1"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=passcode
    expose:
      - 5432

  web:
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:passcode@db:5432/launchpad_develop
    image: assemble/launchpad
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
      - webpack
    volumes:
      - .:/app
      # Docker access on Linux
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker access on OS X
      - ${DOCKER_CERT_PATH:-/certs}:${DOCKER_CERT_PATH:-/certs}

  webpack:
    env_file: .env
    image: assemble/web
    command: /app/bin/webpack-dev-server --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3035:3035
