version: "2.1"

services:
  clock:
    command: bundle exec clockwork util/clock.rb
    image: assemble/web
    links:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    expose:
      - 5432

  web:
    build: .
    env_file: .env
    image: assemble/launchpad
    command: ./bin/serve
    ports:
      - "3000:3000"
    links:
      - db
      - webpack
    volumes:
      - .:/app
      # Docker access on Linux
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker access on OS X
      - ${DOCKER_CERT_PATH:-/certs}:${DOCKER_CERT_PATH:-/certs}

  webpack:
    env_file: .env
    image: assemble/web
    command: /app/node_modules/.bin/webpack-dev-server --config config/webpack.config.js --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8888:8888

  worker:
    env_file: .env
    image: assemble/web
    command: rake jobs:work
    links:
      - db
    volumes:
      - .:/app
      # Docker access on Linux
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker access on OS X
      - ${DOCKER_CERT_PATH:-/certs}:${DOCKER_CERT_PATH:-/certs}
